In [2]:
import firebase_admin
from firebase_admin import credentials, firestore
import pandas as pd
import os

In [8]:
# Caminho relativo do notebook para a pasta .env
CREDENTIAL_PATH = os.path.join('..', '.env', 'serviceAccountKey.json')

In [10]:
# Inicializa o Firebase Admin com a chave da pasta .env
if not firebase_admin._apps:
    cred = credentials.Certificate(str(CREDENTIAL_PATH))
    firebase_admin.initialize_app(cred)

In [11]:
# Inicializa o Firestore
db = firestore.client()

In [23]:
# Caminho relativo do notebook para a pasta .data
CSV_PATH = os.path.join('..', 'data', 'cloud_input', 'water_potability_without_target.csv')

In [24]:
# Leitura do csv
df = pd.read_csv(CSV_PATH)

In [26]:
df.head(30)

,ph,Hardness,Solids,Chloramines,Sulfate,Conductivity,Organic_carbon,Trihalomethanes,Turbidity,Potability
0,8.316766,214.373394,22018.41744,8.059332,356.886136,363.266516,18.436525,100.341674,4.628771,NaN
1,9.092223,181.101509,17978.98634,6.546600,310.135738,398.410813,11.558279,31.997993,4.075075,NaN
2,5.584087,188.313324,28748.68774,7.544869,326.678363,280.467916,8.399735,54.917862,2.559708,NaN
3,10.223862,248.071735,28749.71654,7.513408,393.663395,283.651634,13.789695,84.603556,2.672989,NaN
4,8.635849,203.361523,13672.09176,4.563009,303.309771,474.607645,12.363817,62.798309,4.401425,NaN
5,11.180284,227.231469,25484.50849,9.077200,404.041635,563.885481,17.927806,71.976601,4.370562,NaN
6,7.360640,165.520797,32452.61441,7.550701,326.624353,425.383420,15.586810,78.740016,3.662292,NaN
7,7.119824,156.704993,18730.81365,3.606036,282.344050,347.715027,15.929536,79.500778,3.445756,NaN
8,6.347272,186.732881,41065.23476,9.629596,364.487687,516.743282,11.539781,75.071617,4.376348,NaN
9,9.181560,273.813807,24041.32628,6.904990,398.350517,477.974642,13.387341,71.457362,4.503661,NaN
10,9.445130,145.805402,13168.52916,9.444471,310.583374,592.659021,8.606397,77.577460,3.875165,NaN
11,9.024845,128.096691,19859.67648,8.016423,300.150377,451.143481,14.770863,73.778026,3.985251,NaN
12,6.800119,242.008082,39143.40333,9.501695,187.170714,376.456593,11.432466,73.777275,3.854940,NaN
13,7.174135,203.408935,20401.10246,7.681806,287.085679,315.549900,14.533510,74.405616,3.939896,NaN
14,7.657991,236.960889,14245.78912,6.289065,373.165363,416.624189,10.464239,85.852769,2.437296,NaN
15,8.322987,207.252462,28049.64628,8.827061,297.813085,358.725869,18.709273,60.911420,4.052136,NaN
16,9.802721,98.771644,27357.45674,9.218150,323.199076,512.428731,14.168934,59.454440,2.764634,NaN
17,6.101955,215.268090,15976.92623,8.857160,308.482695,417.843553,13.147279,62.505642,3.535596,NaN
18,4.997771,280.082411,26849.19474,6.130757,374.232961,297.611540,15.571571,70.560275,3.404633,NaN
19,4.815767,217.687093,16392.13507,7.461170,278.742296,481.480828,15.517296,77.693374,4.375224,NaN

In [27]:
# Nome da coleção
collection_name = 'devops-eml1-ex2'

In [28]:
# Upload linha a linha
for i, row in df.iterrows():
    doc_ref = db.collection(collection_name).document(str(i))  # ID opcional
    doc_ref.set(row.to_dict())

print("✅ Upload concluído com sucesso para a coleção:", collection_name)

✅ Upload concluído com sucesso para a coleção: devops-eml1-ex2